config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "window#index"
  resources :tweets, only:[:index, :new, :create, :edit, :update, :destroy]
  resources :blog, only:[:index, :new, :create, :show, :edit, :update, :destroy] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, :content, presence: true
  
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to blog_index_path
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to blog_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to blog_index_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all
  end

  def new
    @tweet =Tweet.new
  end

  def create
    Tweet.create(tweet_params)
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

 
  private
  def tweet_params
    params.require(:tweet).permit(:name, :image, :text)
  end
end

app/controllers/window_controller.rb
class WindowController < ApplicationController

  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/window_helper.rb
module WindowHelper
end

app/views/blog/edit.html.haml
.content__title
  投稿の編集

= form_with  url:blog_path,model:@post, class: :form, local: true do |form|
  = form.text_field :title, placeholder: :タイトル, class: :form__title
  = form.text_area :content, placeholder: :ブログ本文, class: :form__text
  = form.submit '編集する', class: :form__btn

app/views/blog/index.html.haml
= render partial: 'shared/headerA'

.Link
  = link_to("新規投稿", new_blog_path, class: "Link_new")

.Body
  = render partial:'shared/left-content'
  - @posts.each do |post|
    .Body__Content
      = link_to post.title, blog_path(post.id), class:"content"
      = post.created_at











= render partial: 'shared/footerA'

app/views/blog/new.html.haml
= render partial: 'shared/headerA'
.test
  新規記事の作成

.Bodyb
  = form_with url:blog_index_path,model: @post, class: :form, local: true do |form|
    = form.text_field :title, placeholder: "タイトル", class: :form__title
    = form.text_area :content, placeholder: "ブログ本文", class: :form__text
    = form.submit '投稿する', class: :form__btn


= render partial: 'shared/footerA'

app/views/blog/show.html.haml
= render partial: 'shared/headerA'


.Bodya
  .Bodya__content 
    .Bodya__content__title
      = @post.title
    .Bodya__content__dete
      = @post.created_at
    .Body__content__manage
      = link_to "編集", edit_blog_path(@post.id), class: "postManage__edit"
      = link_to "削除", blog_path(@post.id), method: :delete, class:"postManage__delete"
    .Bodya__content__coment
      = simple_format @post.content









= render partial: 'shared/footerA'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PetsResucue
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    -# - if user_signed_in?
    -#   = link_to "ログイン", new_user_session_path, class: "header__right--btn" 
    -#   = link_to "新規登録", new_user_registration_path, class: "header__right--btn"
    = yield

app/views/shared/_footerA.html.haml
.Footer

app/views/shared/_headerA.html.haml
.Header
  = link_to("ペットレスキュー", root_path, class: "Header_link")

app/views/shared/_left-content.html.haml
.Body__left-content  
  %p 【レスキューメニュー】
  %li.Body__left-content__menu
    = link_to("殺処分のデータとか？", root_path, class: "Body__left__content__menu__link")
  %li.Body__left-content__menu
    = link_to("みんなの保護速報（ツイート）", tweets_path, class: "Body__left__content__menu__link")
  %li.Body__left-content__menu
    = link_to("各保護団体ブログ", blog_index_path, class: "Body__left__content__menu__link")
  %li.Body__left-content__menu
    = link_to("保護団体リンク", root_path, class: "Body__left__content__menu__link")
    

app/views/tweets/_tweets.html.haml
%span= image_tag 'arrow_top.png'
        %ul.more_list
          %li 
            = link_to "編集", edit_tweet_path(tweets.id), class:"tweet_edit"
          %li
            = link_to "削除",tweet_path(tweets.id), method: :delete
            = simple_format(tweets.text)
        = tweets.text
        = tweets.name
      

app/views/tweets/create.html.haml
= render partial: 'shared/headerA'

.Success
  投稿が完了しました。
  %a.btn{:href => "/tweets"}投稿一覧へ戻る


= render partial: 'shared/footerA'

app/views/tweets/destroy.html.haml
.Success
  削除が完了しました。
  %a.btn{:href => "/tweets"}投稿一覧へ戻る

app/views/tweets/edit.html.haml
.edit
  投稿の編集

= form_with url:tweet_path,model:@tweet, class: :form, local: true do |form|
  = form.text_field :name, placeholder: "Nickname"
  = form.text_field :image, placeholder: "Imege Url"
  = form.text_area :text, placeholder:"text", rows: "10"
  = form.submit "編集する"

app/views/tweets/index.html.haml
= render partial: 'shared/headerA'



.Body
  -#= render partial: 'shared/left-content'
  -#.Body__new
  = link_to("新規投稿", new_tweet_path, class: "Body__new")
  .Body__content
    - @tweets.each do |tweets|
      .content_post{:style =>"background-image:url(#{tweets.image});"}

        %span= image_tag 'arrow_top.png'
        %ul.more_list
          %li 
            = link_to "編集", edit_tweet_path(tweets.id), class:"tweet_edit"
          %li
            = link_to "削除",tweet_path(tweets.id), method: :delete
        = simple_format(tweets.text)
        = tweets.text
        = tweets.name
      




= render partial: 'shared/footerA'

app/views/tweets/new.html.haml
= render partial: 'shared/headerA'

= render partial: 'shared/left-content'

.Container
  = form_with url:tweets_path, model:@tweet, local: true do |form|
    投稿する
    = form.text_field :name, placeholder: "Nickname"
    = form.text_field :image, placeholder: "Image Url"
    = form.text_area :text, placeholder: "text", rows: "10"
    = form.submit "SEND"

= render partial: 'shared/footerA'

app/views/tweets/update.html.haml
.tweet.update
  更新が完了しました。
  %a.btn{:href => "/"}投稿一覧へ戻る

app/views/window/index.html.haml
= render partial: 'shared/headerA'
.Body
  = render partial: 'shared/left-content'
    
  .Body__content
    .main
      ここに殺処分の説明書いてもイイかも

= render partial:'shared/footerA'